{% set name = "activitysim" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/activitysim-{{ version }}.tar.gz
  sha256: 9bd75d82458d56af643ed16d4bcf20ca4f3014ef80443d14cbfd984ade3cce47

build:
  number: 0
  noarch: python
  entry_points:
    - activitysim=activitysim.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - c-blosc2
    - cytoolz ~=0.12.0
    - numba ~=0.56.0
    - numpy ~=1.23.0
    - openmatrix >=0.3.4.1
    - orca >=1.6
    - pandas >=1.1.0,<2
    - psutil ~=5.9.0
    - pyarrow >=11.0
    - python >=3.9
    - pyyaml >=5.1
    - requests >=2.7
    - pytables ~=3.8.0
    - simwrapper
    - pypyr
    - sharrow >=2.2.4
    - scikit-learn >=1.1
    - xarray

test:
  imports:
    - activitysim
    - activitysim.abm
  commands:
    - pip check
    - activitysim --help
  requires:
    - pip

about:
  home: https://github.com/activitysim/activitysim
  summary: Activity-Based Travel Modeling
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jpn--
